.eslintrc
package.json

Note that _eslint_ had to be bumped to 1.8.0 due to the `no-arrow-condition` rule.
Deprecates #4.
R=@ruiquelhas

Add missing ES6 rules

---

.eslintrc
README.md
package.json

This PR adds a new dependency — the babel eslint plugin — which allows us to correctly use async arrow functions:
```js
it('should work', async () => {
await something();
});
```
This plugin is needed because Babel [has stated](https://github.com/eslint/eslint/issues/3354#issuecomment-129935329) that they can't handle this natively and moved this responsibility to [eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel/issues/8).
Note that this only works because `arrow-parens` was already disabled (incorrectly) here: https://github.com/seegno/eslint-config-seegno/compare/bugfix/fix-async-arrow-functions?expand=1#diff-1dc6ee56b778cd91e0327b52aaeaa1b9R18

Fix async arrow functions

---

.eslintrc

This allows us to do:
```js
const request = () => ({ body: {}, statusCode: 200 });
```
See [relevant rule](http://eslint.org/docs/rules/func-style).

Fix arrow function in variable declarations

---

.eslintrc

- Update `arrow-parens` rule to make the use of parenthesis required on every arrow
function.
- Fixes #6

Update `arrow-parens` rule

---

.eslintrc

Remove `no-ternary` rule

---

.eslintrc

This PR removes duplicated `prefer-spread` and `prefer-template` rules, added with #5. This is related with [js-yaml](https://github.com/nodeca/js-yaml/commit/9ea29ec6aa5e48d3dff3eacf7582818643a0ab0c), which handles duplicated key mapping with exceptions, after release **3.5.0**.
Fixes #21.

Remove duplicated rules

---

src/index.js

Complexity should not be determined by the linter.
Closes #24.

Disable max-nested-callbacks rule

---

src/index.js

Complexity should not be determined by the linter.

Disable complexity rule

---

src/index.js

Follow [2016's resolution]( https://github.com/seegno/eslint-config-seegno/issues/6#issuecomment-169735727) of removing gratuitous arrow parethenses, I'd like to re-evaluate the need for the "always" rule.

Require arrow parentheses as needed

---

src/index.js

It's finally a reality!
Current sort order:
```js
// none
import 'my-module.js';
// all
import * as foo from 'src';
// single default
import _ from 'lodash';
// single named
import { activity } from '../enums';
// multiple named (case and member order matters)
import { A, B, C, a } from 'validator.js';
```
On a side note, the default sort order of eslint is `["none", "all", "multiple", "single"]` instead of `["none", "all", "single", "multiple"]`. If you have a strong opinion about the form, please let us know on this PR.
The example above would become:
```js
// none
import 'my-module.js';
// all
import * as foo from 'src';
// multiple named (case and member order matters)
import { A, B, C, a } from 'validator.js';
// single default
import _ from 'lodash';
// single named
import { …
```

Add rule to sort imports

---

src/index.js
test/index.js

This PR adds exported recommended configuration of _sort-class-members_ plugin and removes previous custom configuration.
Closes #42.

Add recommended configuration of sort-class-members plugin

---

src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

The default setting of this rule enforces the following style:
```js
keyword {
//
} keyword {
//
}
```
This is the style we use, so we might as well add this rule, so that it gets documented.
More info: http://eslint.org/docs/rules/brace-style.

Add `brace-style` rule

---

src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

This rule, in addition to the already existing `one-var`, makes JSCS's `requireLineBreakAfterVariableAssignment` redundant. So this PR is one small step towards removing our JSCS config for good.

Add `one-var-declaration-per-line` rule

---

package.json
src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

Add the `sql-template/no-unsafe-query` rule, from the new project [`eslint-plugin-sql-template`](https://github.com/uphold/eslint-plugin-sql-template), ported from [`jscs-preset-seegno`](https://github.com/seegno/jscs-preset-seegno).
Getting this rule in our eslint config finally makes it reliable enough for it to be safe for us to drop JSCS from our projects.

Add sql template plugin and `sql-template/no-unsafe-query` rule

---

package.json
src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

This PR adds the [sort-imports-es6](https://github.com/erikdesjardins/eslint-plugin-sort-imports-es6) plugin, which overrides the [sort-imports](http://eslint.org/docs/rules/sort-imports) rule. 
The rule is now configured according to @joaogranado suggestion on #43:
```js
import 'module-1';
import * as F from 'module-2';
import { E, d } from 'module-3';
import { c } from 'module-4';
import B from 'module-5';
import a from 'module-6';
```
Closes #43

Update sort-imports rule

---

package.json
src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js

This removes the `eslint-plugin-babel` as the features we are using have been absorbed by `eslint` namely  [generator-star-spacing](http://eslint.org/docs/rules/generator-star-spacing) and [arrow-parens](http://eslint.org/docs/rules/arrow-parens).
`babel-eslint` has been bumped to 7.1.1.
Refs #65

Remove eslint-plugin-babel

---

src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

May this be an interesting rule for the linter to enforce? It is one that we are enforcing on code reviews.

Enforce the newline-before-return rule

---

test/fixtures/environment.js
test/fixtures/incorrect.js
test/index.js

This PR:
* Adds a few rules that were missing from the tests.
* Fixes a few issues in our fixtures that were triggering duplicate rules.
* Improves the tests by making sure that the exact list of rules is expected (and not a subset).

Add missing rules and improve tests

---

package.json
src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

This PR replaces the `sorting-plugin` with the `sort-keys` rule which is available since _eslint 3.3.0_.
The motivation for this change is to respect the team's _natural_ sort order requirement. Also, it's one less dependency (yay!).
Example that did not trigger an error with `sorting-plugin` (and was not configurable):
```js
{
var1: 'foo',
var10: 'foo',
var2: 'foo',
var9: 'bar'
};
```
Using the new `sort-keys` rule, the object would have to be written as:
```js
{
var1: 'foo',
var2: 'foo',
var9: 'bar',
var10: 'foo'
};
```
😌

Replace sorting plugin with sort keys

---

src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js

This PR enables the [require-await](http://eslint.org/docs/rules/require-await) rule, preventing `async` functions to have an `await` expression.

Enable `require-await` rule

---

package.json
src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js

This PR updates eslint to version `v4.7.2`.
It also updates `padded-blocks` and `space-before-function-paren` rules.

Update eslint to version v4.7.2

---

src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

This PR adds `jasmine` and `jest` environments, allowing its globals when using Jest as test framework.
Closes #71

Add jasmine and jest environments

---

src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

Add [`capitalized-comments`](http://eslint.org/docs/rules/capitalized-comments) to require comments to be capitalized. This only applies to the first line of the comment (see `test/fixtures/` for examples of valid/invalid code).
This requires the latest minor version of eslint available as of this PR's creation moment (3.11).

Add `capitalized-comments` rule

---

test/fixtures/environment.js

This PR fixes a small typo in the `environment.js`.

Fix typo in environment.js

---

package.json
src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

This PR adds [eslint-plugin-switch-case](https://www.npmjs.com/package/eslint-plugin-switch-case) and the following rule:
- `newline-between-switch-case`.

Add switch-case plugin and rules

---

package.json
src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

This PR adds the [eslint-plugin-new-with-error](https://github.com/Trott/eslint-plugin-new-with-error) and the respective rule.
This will enforce the user to throw `Error` objects using `new`.   
This is only stylistic and to improve code base standards has there's no difference between creating Error objects with function call or `new`:
https://www.ecma-international.org/ecma-262/8.0/index.html#sec-error-objects

Add new-with-error plugin and rules

---

package.json
src/index.js

This PR updates the `eslint-plugin-sort-destructure-keys` dependency to add the `caseSensitive` option to the `sort-destructure-keys` rule, to make it consistent with other sorting rules.

Fix sort destructure keys rule

---

src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

This PR fixes the __empty case clauses__ from needing an _empty line_ between them.
This bug was introduced in #83.
__The following example, although correct, throws an error:__
```js
switch ('foo') {
case 'foo': // Fix: Newline required between switch cases.
case 'bar':
return 'biz';
default:
return null;
}
```

Fix newline-between-switch-case fallthrough

---

src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

This PR adds `react/jsx-tag-spacing` rule from [eslint-plugin-react
](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-tag-spacing.md)
The following patterns are not considered problems:
```jsx
<FooBar />
<FooBar></FooBar>
````
The following patterns are considered problems:
```jsx
<FooBar/>
<FooBar/ >
<FooBar>< /FooBar>
<FooBar></FooBar>
```

Add react jsx-tag-spacing rule

---

src/index.js
test/fixtures/correct.js
test/fixtures/incorrect.js
test/index.js

This PR adds `react/prefer-stateless-function` rule from [eslint-plugin-react
](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md)
The following pattern is not considered problem:
```jsx
class FooBar extends React.Component {
getFoo = () => {
return 'foo';
}
render() {
return this.getFoo();
}
}
````
The following pattern is considered problem:
```jsx
class FooBar extends React.Component {
render() {
return null;
}
}
```

Add react prefer-stateless-function rule

---

.eslintrc.js
package.json
yarn.lock

This PR adds a pre-commit hook that runs `eslint` and `sort-package-json` on staged files using `lint-staged`.
This also adds a `.eslintrc.js` file that exports `src/index.js`, to support editor integrations and so that it's not necessary to pass `--config src/index.js` when running `eslint`.

Add pre-commit hook

---

package.json
yarn.lock

This PR updates `eslint-plugin-react-hooks` dependency to fix compatibility with @typescript-eslint/parser.
- https://github.com/facebook/react/pull/19751#issuecomment-690621541

Update eslint-plugin-react-hooks dependency

---

.travis.yml
package.json
yarn.lock

This PR fixes a eslint `false positive` that was triggering `no-unused-vars`error on for loops.
The issue is fixed by upgrading to `babel-eslint` to latest (10.1.0) and `eslint` to last of 6 (6.8.0).
**Note**: Support for `Node 8` is also dropped in this version due to `chakl` dependency:
```
=> Found "inquirer#chalk@4.1.0"
info This module exists because "eslint#inquirer" depends on it.
```

Fix no-unused-vars false positive on for loops
